id: I69AAA694
legacy_id: P008212
ocr_import_info:
  bdrc_scan_id: W2CZ5991
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T20:27:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:01:32.137674+00:00'
last_modified: 2022-09-02 23:02:14.240021
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ5991
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ5991
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྟག་ཚང་རས་པའི་རྣམ་ཐར་དང་རྡོ་རྗེའི་མགུར།
  author: སྟག་ཚང་རས་པ་ངག་དབང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.4757462287959096
  ocr_word_median_confidence_index: 0.4099999964237213
quality: null
bases:
  I2DB65257:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2DB65257
      total_pages: 364
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2DB65257.txt
    statistics:
      ocr_word_median_confidence_index: 0.4099999964237213
      ocr_word_mean_confidence_index: 0.4757462287959096
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
