id: I69AAA694
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:29:08+00:00'
last_modified: '2022-06-09T05:16:47.944629+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ5991
  title: སྟག་ཚང་རས་པའི་རྣམ་ཐར་དང་རྡོ་རྗེའི་མགུར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C654:
      image_group_id: I2DB65257
      title: ''
      total_pages: 364
      order: 1
      base_file: C654.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
